apiVersion: apps/v1
kind: Deployment
metadata:
  name: caffeine-ws
  namespace: caffeine
  labels:
    app: caffeine-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caffeine-app
  template:
    metadata:
      labels:
        app: caffeine-app
    spec:
      containers:
      - name: web-service
        image: webservice-app
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: caffeine-service-ws
  namespace: caffeine
spec:
  selector:
    app: caffeine-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100