apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: caffeine
spec:
  containers:
    - name: nginx-container
      image: test
      imagePullPolicy: Never
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: caffeine
spec:
  selector:
    app: caffeine-db
  clusterIP: None
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80